### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#9]
The app doesn't show the spread with `Show Results after delay` deactived. I know that the opposite case is normal, but i think that this way isn't normal.

Search `Show Results after delay`: http://i.imgur.com/sIhqFmV.png

Search without `Show Results after delay`: http://i.imgur.com/xCHgD7T.png

**Comment by wwwwwwzx** [comment]
This is not a bug, I noticed this problem when I was coding. You can try that frame and you will get the spread match perfectly with `Show Results after delay `. Since those target frames are near the blinking(You can check the `Frame After Delay`) and the blinking status will affect UBs' generation. So the frame just after using honey(w/ `Show Results after delay ` checked) is a "better" starting frame than the frame begins to determinate UB appearance (w/o `Show Results after delay ` checked)

**Comment by Real96** [comment]
Uh, understood now, I'm closing this. Thanks a lot!

**Comment by wwwwwwzx** [comment]
No Problem, I'm gonna attack Tapus Synchronize problem now.

**Comment by Real96** [comment]
Great!
